package org.learn.spring.selenium;

// Generated by Selenium IDE


import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.ITestContext;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;

public class InsuranceSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  ChromeOptions chromeOptions;

  @BeforeSuite
  public void setUp(ITestContext context) {


    WebDriverManager.chromedriver().setup();
    chromeOptions = new ChromeOptions();
    //chromeOptions.addArguments("--no-sandbox");
    chromeOptions.addArguments("--headless");
    //chromeOptions.addArguments("disable-gpu");


    
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

  }
  @AfterSuite
  public void tearDown() {
    driver.quit();
  }
  @Test(description = "Insurance Customer Test",priority = 1)
  public void insurancecustomer() {
    // Test name: insurancecustomer
    // Step # | name | target | value
    // 1 | open | /insurance |

    // 3 | waitForElementVisible | id=first-name | 5
   /* {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("first-name"))).sendKeys("arun");
    }
    // 4 | waitForElementVisible | id=last-name | 5
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("last-name"))).sendKeys("arun");
    }
    // 5 | waitForElementVisible | id=middle-name | 5
   *//* {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("middle-name")));
    }*//*
    // 6 | waitForElementNotVisible | id=address | 5
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("address"))).sendKeys("arun");
      
    }*/
    driver = new ChromeDriver(chromeOptions);
    driver.get("http://localhost:4500/insurance");
    
    // 2 | setWindowSize | 1421x1299 |
    driver.manage().window().setSize(new Dimension(1421, 1299));
    driver.findElement(By.id("first-name")).click();
    driver.findElement(By.id("middle-name")).click();
    driver.findElement(By.id("last-name")).click();
    driver.close();
  }

  @Test(description = "customersavetest",priority = 2)
  public void customersavetest() {
    driver = new ChromeDriver(chromeOptions);
    driver.get("http://localhost:4500/insurance");
    driver.manage().window().setSize(new Dimension(1730, 1299));
    driver.findElement(By.id("first-name")).click();
    driver.findElement(By.id("first-name")).sendKeys("arun");
    driver.findElement(By.id("last-name")).sendKeys("shakya");
    driver.findElement(By.id("middle-name")).sendKeys("s");
    driver.findElement(By.id("address")).sendKeys("1111 hello st");
    driver.findElement(By.id("next-btn")).click();
 
    driver.findElement(By.id("vin")).click();
    driver.findElement(By.id("vin")).sendKeys("1111");
    driver.findElement(By.id("make")).click();
    driver.findElement(By.id("make")).sendKeys("111");
    driver.findElement(By.id("model")).click();
    driver.findElement(By.id("model")).sendKeys("11");
    driver.findElement(By.id("year")).click();
    driver.findElement(By.id("year")).sendKeys("1111");
    driver.findElement(By.id("next-btn")).click();
    driver.close();
  }
}

